name: diffeo_cnn_clark
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - numpy
  - jax=0.4.23
  - scipy
  - pandas
  - scikit-learn
  - pillow=10.3.0
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - opencv=4.9.0

